### ISSUE TITLE
Retention by time

### ISSUE THREAD

**Issue by Delagen** [nw/stream-rotate#3]
I think that retention should be calculated in round timing.
For example:
Retention time: 1d
Open stream time: 10:00:00
Retention expire is: next day 10:00:00
Should be better if it will be next day: 00:00:00

**Comment by Delagen** [comment]
Line 133 should be I think: 
```
later = moment(self._stat.ctime).startOf(parts[1]).add(parts[2], parts[1]);
```
May be configuration param if you think))

**Comment by nw** [comment]
If you submit a pull request I'll get this package updated
